config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 
  authenticated :user do
    root 'items#index', as: :authenticated_root
  end
  root to: "splash#index"
  get 'splash', to: 'splash#index', as: 'splash'
  resources :items do
    resources :expenses, only: [:index, :new, :create ,:show]
  end

  resources :expenses, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :expense_items
  has_many :items, through: :expense_items
end

app/models/expenseItem.rb
class ExpenseItem < ApplicationRecord
  belongs_to :expense
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :expense_items
  has_many :expenses, through: :expense_items

  has_one_attached :icon
  validates :name, presence: true
end

app/models/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenses_Controller.rb
class ExpensesController < ApplicationController
  before_action :set_item

  def index
    @expenses = @item.expenses.order(created_at: :desc)
    @total_amount = @expenses.sum(:amount)
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = @item.expenses.build(expense_params)
    @expense.user = current_user
    if @expense.save
      redirect_to item_expenses_path(@item) , notice: 'expense was successfully created.'
    else
      puts "Errors: #{@expense.errors.full_messages}"
      render 'new'
    end
  end
  private

  def set_item
    @item = Item.find(params[:item_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :item_id)
  end
end

app/controllers/items_Controller.rb
# app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = current_user.items.includes(:expenses)
  end

  def show
    @item = Item.find(params[:id])
    @expenses = Expense.where(item_id: params[:id]).order(created_at: :desc)
    @total_amount = @expenses.sum(:amount)
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to items_path, notice: 'Item was successfully created.'
    else
      render 'new'
    end
  end


  private

  def item_params
    params.require(:item).permit(:name, :icon)
  end

  # def expense_params
  #   params.require(:expense).permit(:name, :amount ,:item_id)
  # end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/expenses/_form.html.erb
<%= form_for [@item, @expense] do |f| %>
  <%= f.hidden_field :item_id, value: @item.id %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>
 <div class="submit-button-container">
    <%= f.submit 'Save Expense' , class: "submit-button" %>

    <%= link_to 'Back', items_path  , class: "submit-button"%>
  </div>
<% end %>

app/views/expenses/new.html.erb
<h1>Add a New Expense</h1>

<%= render 'form' %>

app/views/items/_form.html.erb
<%= form_for @item, html: { multipart: true } do |f| %>
  <div class="field ">
  <%= f.label :name %>
  <%= f.text_field :name %>
    </div>

  <div class="field ">
  <%= f.label :icon %>
  <%= f.file_field :icon %>
    </div>

 <div class="submit-button-container">
  <%= link_to 'Back', items_path  , class: "submit-button"%>

  <%= f.submit 'Save' , class: "submit-button" %>
  </div>
<% end %>

app/views/items/index.html.erb
<div class="headRegister"> 
<div>
<%= link_to items_path, class: "btn btn-primary" do %>
  <i class="fas fa-bars"></i>
<% end %>
</div>
<div>My Items</div>
<div>Next</div>
</div>

<div>
  <% @items.each do |item| %>
    <div class="itemCardDiv"> 
    <div class="itemCard">
   <div class="icon_Name"> 
    <div> 
    <% if item.icon.attached? %>
        <%= image_tag item.icon ,class:"icon"%>
      <% else %>
        No Icon Available
      <% end %>
    </div>
    <div class="item_name">   
     <%= link_to item.name, item_path(item) %>
    </div> 
   </div>
    <div class="item_expenses_sum"> 
    <strong> $<%= Expense.where(item_id: item.id).sum(:amount) %> </strong> 
     </div> 
    </div>
    </div>
  <% end %>
</div>
 <div class="submit-button-container">
<%= link_to 'Add a New Item', new_item_path  , class: "submit-button" %>
</div>

app/views/items/new.html.erb
<h1>Create a New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="headRegister"> 
<div>
<%= link_to items_path, class: "btn btn-primary" do %>
  <i class="fas fa-chevron-left"></i>
<% end %>
</div>
<div>Transaction</div>
<div>Next</div>
</div>
<div class="headTrans">
Expenses for <%= @item.name %> <br>
Total Amount: $<%= @total_amount %>
</div>

<div>
  <% @expenses.each do |expense| %>
   <div class="itemCardDivEx"> 
    <div class="itemCard">
 <%= expense.name %> - Amount: $<%= expense.amount %>
    </div>
     </div> 
  <% end %>
</div>
 <div class="submit-button-container">
<%= link_to 'Add a New Expense', new_item_expense_path(@item) , class: "submit-button" %>
<%= link_to 'Back to Items', items_path , class: "submit-button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Add this line to the head section -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Budget Manager</title>
</head>
<body class="body">
 <h1 class="splashtext">Welcome to Budget Manager</h1>
  <p>Track and manage your budget with ease!</p>
  <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn1" %>
  <%= link_to 'Log In', new_user_session_path, class: "btn btn-secondary btn1 " %>
</body>
</html>